//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L.S.DAL.Model.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string ID { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public string ParentID { get; set; }
    }
}
