//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L.S.DAL.Model.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public string ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string Remark { get; set; }
    }
}
